//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sprAirport.Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flights
    {
        public int Id { get; set; }
        public int RouteId { get; set; }
        public int AircraftId { get; set; }
        public System.DateTime DepartureDate { get; set; }
        public System.DateTime ArrivalDate { get; set; }
        public int TicketsSold { get; set; }
    
        public virtual Aircrafts Aircrafts { get; set; }
        public virtual Routes Routes { get; set; }
    }
}
